### ISSUE TITLE
Is README right?

### ISSUE THREAD

**Issue by theverytak** [OpenChannelSSD/qemu-nvme#42]
Hello ocssd experts,

I was using qemu-nvme version 1.2 for some reasons, but I decided to try 2.0. So I was following the steps written on readme file, in this repo, and I can't step forward now.
I have installed qemu, and I made backend file(8GB), and vm image file correctly. Then I used these options :
 `sudo $HOME/qemu-nvme/bin/qemu-system-x86_64 -m 4G -smp 4 -s \
-drive file={path to vm image},id=diskdrive,format=raw,if=none \
-device virtio-blk-pci,drive=diskdrive,scsi=off,config-wce=off,x-data-plane=on \
-drive file={path to ocssd backend file},id=myocssd,format=raw,if=none \
-device nvme,drive=myocssd,serial=deadbeef,lnum_pu=4,lstrict=1,meta=16,mc=3`
and the qemu is showing "no bootable device" message before running ubuntu.

If I recall correctly, I used -hda option for using vm image. Is the readme tutorial correct? If it does, why can't I go forward? I'd be glad if anyone let me know about the correct options.

Thank you.

**Comment by MatiasBjorling** [comment]
Hi,
You may want to try with:

sudo $HOME/qemu-nvme/bin/qemu-system-x86_64 -m 4G -smp 4 -s \ 
-hda {path to vm image} \ 
-drive file={path to ocssd backend file},id=myocssd,format=raw,if=none \ 
-device nvme,drive=myocssd,serial=deadbeef,lnum_pu=4,lstrict=1,meta=16,mc=3

That disables the fast storage backend for the vm image. It's great to have, but it does require a bit of reconfiguring of the vm to use vda1, instead of sda1, etc.

**Comment by theverytak** [comment]
Yes, this option works.
Maybe you'd better add some lines on readme file.

Thank you for your help!
