### ISSUE TITLE
MLC Flash Support in QEMU

### ISSUE THREAD

**Issue by arnvm** [OpenChannelSSD/qemu-nvme#6]
Hi,

I wish to evaluate LightNVM with MLC Flash. 

But, setting `lfmtype` device flag to any value other than 0 (SLC), QEMU returns following error:   
`nvme: Only SLC Flash is supported at the moment`

Is there any plans to support MLC Flash in qemu-nvme anytime soon?

Thank You

**Comment by MatiasBjorling** [comment]
Hi,

So far we've only exposed SLC due to it being an easier memory to work with. We don't currently plan to add it to QEMU (the next work we would do would be to add OCSSD 2.0 support instead, which abstracts away MLC programming behavior).

You are welcome to send a patch adding MLC support if you like. The steps to implement is to first expose that it is MLC memory, and then populate the MLC lower/upper table defined in the spec. That should do it.

Thank you,
Matias

**Comment by arnvm** [comment]
Thanks for the steps Matias. I really appreciate the help.
