### ISSUE TITLE
Confusing definations of blocks/planes/pages

### ISSUE THREAD

**Issue by arnvm** [OpenChannelSSD/qemu-nvme#7]
Hi,

While going through the [code](https://github.com/OpenChannelSSD/qemu-nvme/blob/master/hw/block/nvme.c#L3200), I came across something that I found confusing. I hope to get some clarification here.  

The comments in [this file](https://github.com/OpenChannelSSD/qemu-nvme/blob/master/hw/block/nvme.c#L3200) say that the divisions are made in the following format:
 `LUNS - BLOCKS - PLANES - PAGES - SECTORS`

![plane](https://user-images.githubusercontent.com/29284950/27536353-5a940c30-5a8c-11e7-9226-c9c2e66d204b.png)

<hr/>

How do you define a `PLANE` in this case?    
   
As per the [conventional definition](https://flashdba.com/2014/06/20/understanding-flash-blocks-pages-and-program-erases/) of a `PLANE`, I would expect the division to be as follows
`LUNS - PLANES - BLOCKS - PAGES - SECTORS`

Pretty sure that that context in which `PLANE` is used in the code is different. Could you please explain what it is? Would I be correct to assume that it is "minimum number of pages that have to be read/written in one request"? (this is again against the [conventional definition](https://flashdba.com/2014/06/20/understanding-flash-blocks-pages-and-program-erases/) of a `PAGE` and hence the confusion)

Thank you

**Comment by javigon** [comment]
Hi,

There are two different things here:

1. A plane is a media abstraction that defines a new level of parallelism. You can think if it as a sub-die in a die, that instead of being exposed as a LUN is exposed as part of a LUN. The plane, allows to do R/W/E in parallel in the same LUN. At the moment, we manage this with a hint sent by the host as part of the command. When we use multi-plane programming (e.g., pblk), the minimum write unit is page across planes, thus the comment. But this is not the general case, as we can also program in a per-plane basis.

2. Since we are using a normal file as a backed, we need to do a transformation from a sparse address space to a linear one. In the diagram you posted you can see how we lay out the data linearly. This is only in QEMU and does not represent real media. 

Does this make sense?

Javier

**Comment by arnvm** [comment]
Ooh! That makes sense. Thanks a lot for the explanation.

**Comment by arnvm** [comment]
I guess the variable names threw me off.
 
[`ln->params.sec_per_pl = ln->params.sec_per_pg * c->num_pln;`](https://github.com/OpenChannelSSD/qemu-nvme/blob/master/hw/block/nvme.c#L3221)
On first glance, it would seem that the value `ln->params.sec_per_pl` stores is the number of "sectors per plane". But its usage indicates that it stores the minimum write unit (across planes). That caused some confusion about the defination of "plane" used in the context. 

Thanks again for the clarification.

**Comment by javigon** [comment]
No problem. Glad that it makes sense now.

Javier
